services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hisaab-backend
#    restart: always
    ports:
      - "7003:7003"
    env_file:
      - .env
    volumes:
      - uploads:/app/uploads
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16-alpine
    container_name: hisaab-postgres
#    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: hisaab
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d hisaab" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  uploads:
  pgdata:

